### ISSUE TITLE
GHC 8.4.1 compatibility

### ISSUE THREAD

**Issue by peti** [phadej/tree-diff#15]
Could you please relax the version constraint on `base` on Hackage to allow for building with GHC 8.4.1?

**Comment by phadej** [comment]
I don't have install-plan due `blaze-builder`, so cannot run tests. See #14

**Comment by peti** [comment]
OK, I see. I've been building (and testing) this package successfully with a patched version of `blaze-builder`, but I realize that is not the same thing as having a proper build succeed.

**Comment by peti** [comment]
I suppose this issue can be closed?
